### ISSUE TITLE
Set up milestone syncing

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#297]
**Background**
We just started using milestones! But it doesn't look like they sync across repos. This issue covers implementing milestone syncing so that we can easily apply the same milestones to both the UX Guide and the Methods to help keep our work aligned.  We created a milestone in the Methods repo, but we want it to also appear in the UX Guide repo. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] implementing milestone syncing

**Tasks**
- [x] review syncing across repos documentation from [wiki](https://github.com/18F/methods/wiki/Syncing-across-repos)
- [ ] possibly pair with an engineer 
- [ ]  PO review [if task involves content changes] 
- [ ]  Accessibility review [if needed]
- [ ]  Outreach approval [if needed]

**Comment by christophermather** [comment]
Transferring over to the new Guides repo, but noting that this work will either 1) be obsolete because of Guides consolidation or 2) need to be rescoped/reconsidered in the new repo. If the latter, I don't believe milestones exist in the new repo: should they? If so, are the UX milestones/milestone process portable?

**Comment by juliaklindpaintner** [comment]
I'm choosing to close this issue for now. There is currently no synchronized work happening across Guides and Methods, and as Chris mentioned in his last comment, the need to sync across repos is (will soon be) obsolete, as all will exist in the guides repo (pending completion of Methods replatforming).
