### ISSUE TITLE
🟢 Add guidance on secret management for cloud.gov apps

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/guides#329]
See Slack threads:
https://gsa-tts.slack.com/archives/CG8SNAEQM/p1600357885059100
https://gsa-tts.slack.com/archives/C02CD5VUQ/p1600358389165400
possibly others.

**Comment by SSPJ** [comment]
@cantsin and @bpdesigns , after reviewing the linked threads and reading this [cloud.gov documentation page](https://cloud.gov/docs/management/production-ready/#protect-access-to-sensitive-credentials), I am not sure that this ticket will provide value to our guides.

My reasoning is:
* the purpose of this ticket is to document best practices for the use of a particular service (cloud.gov)
* best practices may change as technology changes
* the most logical "owner" of documentation on how to use a tool is the team who provides it
* cloud.gov has documentation on this issue
    * _arguably, it could be more clearly written with better examples, but TLC doesn't manage their docs_

I think more broad guidance on secret management in general would be a useful addition, but that's a different scope/focus than this ticket. I could also simply link to cloud.gov's doc page.

What do you think we should do here?

**Comment by cantsin** [comment]
Great points. I agree that a more broad guidance for secret management is out of scope (and perhaps necessarily agency-specific?) 

Will linking to the cloud.gov documentation provide value to our guides? I would leave that call up to you. If so, please add a link, maybe with brief context -- otherwise we can close as is. 

Thanks for flagging!
