### ISSUE TITLE
Add icons to links on Engineering Hiring Guide

### ISSUE THREAD

**Issue by christophermather** [18F/guides#348]
### A description of the work

From the [link audit](https://docs.google.com/spreadsheets/d/1T-J8gAfyuToa7Kzzi2KMAyLxaOJfi6mCW8q5b7ChWYA/edit#gid=536773198) from https://github.com/18F/TLC-crew/issues/341:

Two links on the [Resume Review](https://guides.18f.gov/eng-hiring/resume-review/) page are missing external link icons (see below). External link icons should be added to these links.

Question: are these link icons meant to be added manually? Or do we have an automated process in place? 

- If the latter, we need to investigate what's breaking our automated process for these links. Possibly the fact that these links are inside an alert box?
- If the former, then we just need to manually add external link icons here.

| Text  | Link | Image |
| -- | -- | -- |
| in one study  | https://www.nber.org/digest/sep03/w9873.html | <img width="267" alt="image" src="https://github.com/18F/guides/assets/97245800/c626a41f-2cca-468f-acd7-07b46ad2e0aa"> |
| the Unbias Me | https://chrome.google.com/webstore/detail/unbias-me/bghhadboobnoikppffdojcebigmcgmam?hl=en | <img width="377" alt="image" src="https://github.com/18F/guides/assets/97245800/4c99184c-4650-4e68-b532-9567472db061"> |

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] Both links mentioned above have external link icons 
- [ ] The link format follows the latest accessibility standards that other links on our Guides site do

**Comment by adunkman** [comment]
This should be an automatic task — for this issue, investigate and fix why the automated process isn’t adding icons here.

**Comment by juliaklindpaintner** [comment]
https://github.com/18F/TLC-crew/issues/341 may have more info!

**Comment by caleywoods** [comment]
As I was browsing the prioritized task list this issue caught my eye and I did some quick research since I recalled from the Childcare.gov beta build that the external link icon is added by USWDS when the class `usa-link--external` is present in the elements classlist, that let me do some searching of the guides codebase and here's what I found:

I confirmed Andrew's comment that this process is automatic, [this line of code](https://github.com/18F/guides/blob/8efa56d41516f21be250774760daebe6f70d74ad/.eleventy.js#L159) executed during the Eleventy build process will automatically attach `usa-link` and `usa-link--external` to any link that whose hostname doesn't end in `.gov`. The two examples given by Chris should meet that criteria so the investigation should look into whether or not those links are being passed through that link markdown rendering method or not.

If there's a quick fix needed, the Markdown renderer for Eleventy supports adding classes to elements in the Markdown using the following syntax: `(link text)](link){.usa-link .usa-link--external}`. 

One other thing to note: during my searching of the guides codebase I found several instances of links inside of Markdown files with a hostnmae that ends in `.gov` having the external link class applied to them manually, [like this example](https://github.com/18F/guides/blob/8efa56d41516f21be250774760daebe6f70d74ad/content/methods/fundamentals/privacy.md?plain=1#L32).
